config/routes.rb
Rails.application.routes.draw do
 
  
 root to: 'tasks#index'
 
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout' ,to: 'sessions#destroy'
 
  get 'signup', to: 'users#new'
  resources :tasks
  resources :users, only:[:new,:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :content, presence: true, length: {maximum: 255}
  validates :deadline, presence: true, length: {maximum: 255}
end

app/models/user.rb
class User < ApplicationRecord
    
    validates :name, presence: true, length: {maximum: 50}
    validates :email, presence: true, length: {maximum: 255},
                     format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
                        
    has_secure_password
    has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include SessionsHelper
        
    private
    
    def require_user_logged_in
        unless logged_in?
        redirect_to login_url
        end
    end
    
    def counts(task)
        @count_tasks = current_user.tasks.count
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success]="ログインに成功しました"
      redirect_to root_path
    else
      flash.now[:danger]="ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success]="ログアウトしました"
    redirect_to login_path
  end

  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    
    before_action :set_task, only:[:show, :edit,:update,:destroy]

    
    def index
        if logged_in?
        @task = current_user.tasks.build
        @tasks = current_user.tasks.order(id: :desc).page(params[:page]).per(10)
        counts(@task)

        end
    end
    
    def show
    end
    
    def new
        @task = Task.new
    end
    
    def create
        @task = current_user.tasks.build(task_params)
        if @task.save
        flash[:success] ='投稿できました'
        redirect_to root_url
        else
        flash.now[:danger]='投稿できませんでした'
        render :new
        end
    end
    
    def edit
    end
    
    def update
        @task = Task.find(params[:id])
        if @task.update(task_params)
        flash[:success]='タスクを更新しました'
        redirect_to @task
        else
        flash.now[:danger]='タスクは更新されませんでした'
        render :edit
        end
    end
    
    def destroy
        
        @task.destroy
        
        flash[:success]= 'タスクを削除しました'
        redirect_back(fallback_location: root_path)
    end
    
private
    def set_task
        @task = Task.find(params[:id])
    end
    
    def task_params
        params.require(:task).permit(:content, :deadline)
    end
    
    def correct_user
        @task = current_user.tasks.find_by(id: params[:id])
        unless @task
            redirect_to root_url
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
     if @user.save
       flash[:success]="登録が完了しました"
       redirect_to tasks_path
       
      else
        flash.now[:danger]="登録に失敗した"
        render :new
     end
  end
  
  private
  
  def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
      
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
    @current_user ||= User.find_by(id: session[:user_id])
    end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type,message| %>

<div class="alert alert-<%= message_type %>">
<%= message %>
</div>

<%end%>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">To Do</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        
      
      
      <%if logged_in?%>
        <li class="nav-item">
    <%=link_to '+タスクの投稿',new_task_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
    <%= link_to 'ログアウト',logout_path, method: :delete,class: 'nav-link' %>
        </li>
        <% else %>
        
        <li class="nav-item">
    <%=link_to 'Sign up',signup_path, class: 'nav-link'%>
        </li>
        <li class="nav-item">
    <%=link_to 'Log in',login_path, class: 'nav-link'%>
        </li>
      <% end %>  
      </ul>
      </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>To do</title>
    
<%= csrf_meta_tags %>

    
<%= csp_meta_tag %>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    
<%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    
    <div class="container">
      
      <%= render 'layouts/flash_messages'%>
      
      
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<% if task.errors.any? %>

    <div id="error_explanation"　class="alert alert-warning">

      <ul class="mb-0">
        
<% task.errors.full_messages.each do |msg| %>

          <li>
<%= msg %>
</li>
        
<% end %>

      </ul>
    </div>
  
<% end %>

<div class="row">
    <div class="col-6">

<%= form_with(model: task,local: true) do|f| %>

    <div class="form-group">

<%=f.label :content, 'タスク' %>

<%=f.text_area :content, class: 'form-control' %>

<%= f.select :deadline, [["緊急","緊急"],["早く","早く"],["なるべく早く","なるべく早く"]], include_blank: "ここから選択してください" %>

    </div>

<%=f.submit '投稿', class: 'btn btn-primary'%>

</div>
    </div>
<%end%>

app/views/tasks/edit.html.erb
<h1>id:
    <%= @task.id %>の編集
</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<% if logged_in? %>

<h5> 
<%= current_user.name %>さんのスケジュール
</h5>
<h1>タスク一覧 (<%= @count_tasks %>)</h1>


<%if @tasks.any? %>
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>ステータス（完/末）</th>
            <th>タスク</th>
            <th>優先順位</th>
            <th>要/不要</th>
        </tr>
    </thead>
    <tbody>


<% @tasks.each do|task|%>

    <tr>
<td>
    <%=link_to task.id, task %> 

</td>
<td>
    <input type="checkbox" name="ck01" value="1" autofocus>

</td>    
<td>
    <%=task.content%>
</td>

<td>
    <%=task.deadline%>
</td>
<td>
    <%=link_to'削除', task_path(task.id), method: :delete, data: {confirm: '削除してもいいですか？'}%>
</td>
    </tr>
  

<% end %>

    
    </tbody>
</table>

    <div>
<%= paginate @tasks%>    
    </div>
    
<%end%>


<%=link_to'新規タスクの投稿', new_task_path,class: "btn btn-primary" %>

<% else %>

<div class="container">
  <div class="jumbotron mt-4">
    <h1 class="display-4">To Do</h1>
    <h5 class="lead">課題を忘れて後回しにしていませんか</h5>
    <hr class="my-4">
    <p>タスクを可視化させることでタスクに優先順位をつけよう</p>
    <br>
    <p>スケジュールを管理して日々のタスクを明確にしよう</p>
    <br>
    <p>タスクを消化してスケジュールを円滑にしよう</p>
    
    
    
<% end %>

app/views/tasks/new.html.erb
<h1>タスクの新規作成ページ</h1>

<%= render'form',task: @task %>

app/views/tasks/show.html.erb
<h1>id:
<%= @task.id%>
</h1>

<p>
    <%= @task.content%>
</p>


<%=link_to'タスクの編集',edit_task_path(@task),class: "btn btn-primary"%>
<br>
<%=link_to'タスク一覧に戻る',tasks_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>登録画面</h1>



<div class="row">
    <div class="col-6">

<%= form_with(model: @user, local: true) do|f| %>

        <div class="form-group">
        <%=f.label :name,'名前' %>
        
        <%=f.text_field :name, class: 'form-control' %>
        </div>
        
        <div class="form-group">

        <%=f.label :email,'メールアドレス' %>
        
        <%=f.text_field :email,class: 'form-control' %>
        </div>
        
        <div class="form-group">

        <%=f.label :password,'パスワード' %>
        
        <%=f.text_field :password,class: 'form-control' %>
        </div>
        
        <div class="form-group">

        <%=f.label :password_confirmation,'確認' %>
        
        <%=f.text_field :password_confirmation,class: 'form-control' %>
        </div>
        
        <%= f.submit 'Sign Up', class: 'btn btn-primary btn-block' %>

<% end %>        
</div>
    </div>